#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"

export LD_LIBRARY_PATH="$HERE/usr/lib:$HERE/usr/lib/x86_64-linux-gnu:$HERE/usr/wengine/_internal:$LD_LIBRARY_PATH"

for dir in "$HERE/usr/lib"/python3.*; do
    if [ -d "$dir" ]; then
        export PYTHONHOME="$HERE/usr"
        export PYTHONPATH="$HERE/usr/share/wengine:$dir/site-packages"
        break
    fi
done

for dir in "$HERE/usr/wengine/_internal"; do
    if [ -d "$dir" ]; then
        export PYTHONPATH="$dir:$PYTHONPATH"
        break
    fi
done

for dir in "$HERE/usr/lib"/PySide6/Qt; do
    if [ -d "$dir" ]; then
        export QT_PLUGIN_PATH="$dir/plugins:$QT_PLUGIN_PATH"
        export QT_QPA_PLATFORM_PLUGIN_PATH="$dir/plugins/platforms:$QT_QPA_PLATFORM_PLUGIN_PATH"
        export QML2_IMPORT_PATH="$dir/qml:$QML2_IMPORT_PATH"
        break
    fi
done

export PATH="$HERE/usr/bin:$PATH"

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    export QT_QPA_PLATFORM="wayland;xcb"
else
    export QT_QPA_PLATFORM="xcb"
fi

exec "$HERE/usr/wengine/wengine.bin" "$@"
